module.exports = {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "3",
      name: "Best Pants",
      category: "Pants",
      image: "/d1.jpg",
      price: 80,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
    },
    {
      _id: "4",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "5",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "6",
      name: "Best Pants",
      category: "Pants",
      image: "/d1.jpg",
      price: 80,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
    },
  ],
};
